name: iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Show selected Xcode version
      run: xcodebuild -version
    - name: Run xcodebuild test
      run: |
        set -o pipefail
        xcodebuild clean test -project ios-test-sample/ios-test-sample.xcodeproj -scheme ios-test-sample -destination "platform=iOS Simulator,name=iPhone 11" | xcpretty
